name: squawker
description: An open-source anonymous Twitter client

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html

version: 3.8.4+47

environment:
  sdk: ">=3.9.0 <4.0.0"

dependency_overrides:
  win32: ^5.4.0
  meta: ^1.17.0
  characters: ^1.4.1
  js: ^0.7.2
  test_api: ^0.7.7
  dart_style: ^3.1.2
  _fe_analyzer_shared: ^88.0.0
  analyzer: ^8.1.1
  freezed_annotation: ^3.1.0
  dcli: ^7.0.5
  dcli_common: ^7.0.2
  dcli_core: ^7.0.3
  dcli_terminal: ^7.0.3
  archive: ^4.0.7
  material_color_utilities: ^0.13.0
  strings: ^4.0.1
  sum_types: ^0.4.0
  unicode: ^1.1.8
  asp: ^2.0.3
  triple: ^2.1.0

dependencies:
  flutter:
    sdk: flutter

  async_button_builder: ^3.0.0+1
  http: ^1.2.0
  
  chewie: ^1.7.5
  cryptography: ^2.7.0
  dart_twitter_api: ^0.6.0
  device_info_plus: ^11.5.0
  # device_preview: ^1.1.0 # incompatible with Flutter 3.22.x+
  dotted_border: ^3.1.0
  extended_image: ^10.0.1
  extended_nested_scroll_view: ^6.2.1
  faker: ^2.1.0
  ffcache: ^1.1.0
  file_picker: ^10.3.2
  flex_color_scheme: ^8.3.0
  flutter_cache: ^0.1.0
  # flutter_colorpicker: ^1.0.3
  flutter_colorpicker:
    git:
      url: https://github.com/mchome/flutter_colorpicker
      ref: master # or 786d04363f587b818ce585d25b9c2bb62de95aba
  flutter_file_dialog: ^3.0.2
  flutter_iconpicker: ^4.0.1
  flutter_local_notifications: ^19.4.1
  flutter_localized_locales: ^2.0.5
  flutter_swipe_action_cell: ^3.1.3
  flutter_triple: ^2.2.0
  hex: ^0.2.0
  html_unescape: ^2.0.0
  
  infinite_scroll_pagination: ^5.1.0
  intl: ^0.20.2
  logging: ^1.2.0
  # logging_to_logcat: ^1.0.0 # waiting for the 1.0.3 version...
  logging_to_logcat:
    git:
      url: https://github.com/ChristianKleineidam/logging_to_logcat
      ref: main # or d919298fa9ca4f6d331f2c94547f2c42fb5ba826
  measure_size: ^4.0.0
  media_scanner: ^2.1.0
  multi_select_flutter: ^4.1.3
  package_info_plus: ^8.3.1
  path: ^1.8.3
  path_provider: ^2.1.1
  permission_handler: ^12.0.1
  pref: ^2.7.2
  provider: ^6.1.1
  quiver: ^3.1.0
  receive_sharing_intent: 1.8.1
  scroll_to_index: ^3.0.1
  scrollable_positioned_list: ^0.3.8
  share_plus: ^11.1.0
  shared_preferences: ^2.2.2
  socks5_proxy: ^2.1.0
  sqflite: ^2.4.2
  sqflite_common: ^2.5.4
  sqflite_common_ffi: ^2.3.2+1
  sqflite_migration_plan: ^1.0.0
  synchronized: ^3.1.0+1
  timeago: ^3.6.0
  url_launcher: ^6.2.2
  uuid: ^4.5.1
  video_player: ^2.8.3
  visibility_detector: ^0.4.0+2
  wakelock_plus: ^1.3.2
  no_screenshot: ^0.3.1

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  flutter_oss_licenses: ^3.0.4
  intl_utils: ^2.8.7
  mockito: ^5.4.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  #enabled as some packages require it still
  uses-material-design: true 
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  assets:
    - assets/
  generate: true

flutter_intl:
  enabled: true
  class_name: L10n